### ISSUE TITLE
Hotspot aspect still not quite right

### ISSUE THREAD

**Issue by Wahooney** [leukbaars/DreamUV#10]
I've attached a sample where the aspect of some faces are not correctly calculated (pointed out with the annotation).

[Hotspot Aspect Error.zip](https://github.com/leukbaars/DreamUV/files/4907662/Hotspot.Aspect.Error.zip)

The face I point out keeps getting matched with a square in the atlas.

I hope the attachment helps.

**Comment by leukbaars** [comment]
thank you! I will investigate. That's a very strange bug :S

**Comment by leukbaars** [comment]
So i found the cause of the bug and it will require a bit of code refactoring, but hopefully i'll have a fix out soon.

**Comment by leukbaars** [comment]
Fix checked in!
