### ISSUE TITLE
[Blender 2.93] DreamUV not working in 2.93

### ISSUE THREAD

**Issue by nuclearfessel** [leukbaars/DreamUV#16]
DreamUV is not working in 2.93.

I am assuming this is to this to the updates to the API in 2.93 and is related to Python being upgraded in Blender 2.93 tp version 3.9.1?

**Comment by leukbaars** [comment]
2.93 is still in beta so I usually prefer waiting until it's released before updating the script, but I'll have a look to see if any significant changes are needed

**Comment by nuclearfessel** [comment]
2.93 has been released. Any chance for an update so DreamUV can work in there?

Thanks!

**Comment by leukbaars** [comment]
fixed!
