### ISSUE TITLE
Performance Increase for Meshes with many seams?

### ISSUE THREAD

**Issue by melvixiodf** [leukbaars/DreamUV#23]
Hi,

Any chance for an increase in performance for Dream Uvs when used on a mesh with a lot of seams? Most times it would take not less than 6 hours for it to calculate. Most times I have to break the mesh into multiple parts for it to work faster.

Would appreciate any improvement in the time it takes to hotspot meshes with a lot of seams.

Also UV sync selection affects UVs when hotspotting.

Also thanks for making this addon available for others to use.

**Comment by leukbaars** [comment]
6 hours!!!! You must be working on extremely high triangle counts! I designed this for use with mostly low poly geometry and its been near instant for me. I plan for doing optimisations but it hasn't been a priority so far, and there's only so much I can do anyways with this being a python script..

**Comment by melvixiodf** [comment]
Noted. I don't think it should be high priority but something to adjust in future especially as next gen game engines allow high geometry mesh currently. I just thought it could be something you could consider.

If it is not possible, it is okay, breaking the mesh into smaller parts does the job.

Any chance you can add an option to turn on and off hard edges detection when using DreamUv if you want to use UV seams only? It would be useful if you want the textures over certain hard edges areas and not at the edges.

**Comment by JoelGodin** [comment]
I had 20,000 faces that I hotspotted and it took about 5 minutes.  That is on a new M1 Apple.
I imagine your computer is an older one.

**Comment by melvixiodf** [comment]
> I had 20,000 faces that I hotspotted and it took about 5 minutes. That is on a new M1 Apple. I imagine your computer is an older one.

Nah, I am using a 64gb ram laptop with rtx2080. My mesh had like close to 900,000 faces. 

No worries. Dream uvs is not meant to work with faces that high so I cut it into smaller pieces.
