### ISSUE TITLE
Blender 4.1: AttributeError: 'Mesh' object has no attribute 'auto_smooth_angle'

### ISSUE THREAD

**Issue by EvilReFlex** [leukbaars/DreamUV#40]
Blender changed smoothing and now this error occurs. 

AttributeError: 'Mesh' object has no attribute 'auto_smooth_angle'

**Comment by unfa** [comment]
Yup. I hope someone can fork it and figure it out.

**Comment by leukbaars** [comment]
This should be fixed now, but probably needs a bit of testing, let me know if you encounter any issues

**Comment by EvilReFlex** [comment]
Thanks, it works now.

**Comment by unfa** [comment]
It seems to be fixed, I think we can close this issue now.

**Comment by Radivarig** [comment]
@leukbaars what was the solution? I've hit this on first use on the default cube and a subdivided hotspot plane.

Blender: 4.4.1
DreamUV: 0.9
