### ISSUE TITLE
Error when trying to unwrap Hotspot in 4.2

### ISSUE THREAD

**Issue by udese** [leukbaars/DreamUV#47]
```
Python: Traceback (most recent call last):
  File "/home/udese/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/DreamUV-master/DUV_HotSpot.py", line 500, in execute
    main(context)
  File "/home/udese/.var/app/org.blender.Blender/config/blender/4.2/scripts/addons/DreamUV-master/DUV_HotSpot.py", line 246, in main
    aspect = 1/(round(1/aspect))
             ~^^~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by yankscally** [comment]
I got this too, not sure how I did it though.

**Comment by leukbaars** [comment]
If you have an example file where this happens, that would be very helpful, thanks!

**Comment by yankscally** [comment]
[dreamUVerror.zip](https://github.com/user-attachments/files/17620301/dreamUVerror.zip)

yes, it seems to be this one mesh in my scene. I made a file with just this mesh and the atlases, hope it helps!

**Comment by leukbaars** [comment]
![image](https://github.com/user-attachments/assets/b2bd636a-e376-45fc-b5ce-63403b6cf98a)

This non-manifold face seems to be causing the error. I'll make sure dreamuv just skips these if it encounters them

**Comment by leukbaars** [comment]
this is now fixed
